# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  nhonvttojtminimalapi:
    image: nhonvttojtminimalapi
    build:
      context: .
      dockerfile: NhonVTT-OJT-MinimalAPI/Dockerfile
    ports:
      - 5274:5274
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
